---
- name:  Linux Memory Usage Monitoring and Alert Notification
  hosts: all
  become: true

  tasks:

  - name: "Update all Packages"
    yum:
      name: "*"
      state: latest
                
  - name: "Install Packages"
    yum:
      name:
        - systat
        - bc
      state: present

  - name: 'copy Get-Memory-Utilization.sh script to client servers'
    copy:
      src:  Get-Memory-Utilization.sh
      dest: /tmp
      mode: '0775'

  - name: 'Preparing Memory utilization using script results'
    shell: |
      sh /tmp/Get-Memory-Utilization.sh
    register: memsec


  - name: 'Preparing Memory utilization for 1st sec'
    shell: |
      sh /tmp/Get-Memory-Utilization.sh
    register: mem1sec


  - name: 'Preparing Memory utilization for 2nd sec'
    shell: |
      sh /tmp/Get-Memory-Utilization.sh
    register: mem2sec


  - name: 'Preparing Memory utilization for 3rd sec'
    shell: |
      sh /tmp/Get-Memory-Utilization.sh
    register: mem3sec


  - name: 'Prepare Memory Used percentage if its abnormal'
    shell: |
      sh /tmp/Get-Memory-Utilization.sh
    register: memhigusage
    when: memsec.stdout|int >= 90 or mem1sec.stdout|int >= 90 or mem2sec.stdout|int >= 90 or mem3sec.stdout|int >= 90
  - debug:
      var: memhigusage

  - name: 'Print message if MEMORY utilization become normal'
    debug:
      msg:
        - -------------------------------------------------------
        -  Memory Utilization = ( ( Total - Free ) / Total * 100 ) = {{ memsec.stdout }}%
        - -------------------------------------------------------
    when: memsec.stdout|int < 90 and mem1sec.stdout|int < 90 and mem2sec.stdout|int < 90 and mem3sec.stdout|int < 90

  - name: 'Print message if MEMORY utilization become abnormal'
    debug:
      msg:
         - -------------------------------------------------------
         - Memory Utilization = ( ( Total - Free ) / Total * 100 ) = {{ memhigusage.stdout }}%
         - -------------------------------------------------------
    when: memsec.stdout|int >= 90 or mem1sec.stdout|int >= 90 or mem2sec.stdout|int >= 90 or mem3sec.stdout|int >= 90

  - name: Send Email when MEMORY utilization become abnormal
    when: memhigusage.changed == true
    mail:
      host: smtp.gmail.com
      port: 587
      username: "test1@gmail.com"
      password: "password"
      to: John Sam <johnsam@gmail.com>
      subject: "{{ ansible_hostname }} - Memory Utilization - {{ memhigusage.stdout }}%"
      body: "Memory Utilization = ( ( Total - Free ) / Total * 100 ) = {{ memsec.stdout }}%"
